//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Паспортные данные.
    /// </summary>
    // *** Start programmer edit section *** (паспортные CustomAttributes)

    // *** End programmer edit section *** (паспортные CustomAttributes)
    [AutoAltered()]
    [Caption("Паспортные данные")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("паспортныеДанныеE", new string[] {
            "Серия as \'Серия\'",
            "Номер as \'Номер\'"})]
    [View("паспортныеДанныеL", new string[] {
            "Серия as \'Серия\'",
            "Номер as \'Номер\'"})]
    public class паспортные : ICSSoft.STORMNET.DataObject
    {
        
        private int fСерия;
        
        private int fНомер;
        
        // *** Start programmer edit section *** (паспортные CustomMembers)

        // *** End programmer edit section *** (паспортные CustomMembers)

        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (паспортные.Номер CustomAttributes)

        // *** End programmer edit section *** (паспортные.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (паспортные.Номер Get start)

                // *** End programmer edit section *** (паспортные.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (паспортные.Номер Get end)

                // *** End programmer edit section *** (паспортные.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (паспортные.Номер Set start)

                // *** End programmer edit section *** (паспортные.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (паспортные.Номер Set end)

                // *** End programmer edit section *** (паспортные.Номер Set end)
            }
        }
        
        /// <summary>
        /// Серия.
        /// </summary>
        // *** Start programmer edit section *** (паспортные.Серия CustomAttributes)

        // *** End programmer edit section *** (паспортные.Серия CustomAttributes)
        public virtual int Серия
        {
            get
            {
                // *** Start programmer edit section *** (паспортные.Серия Get start)

                // *** End programmer edit section *** (паспортные.Серия Get start)
                int result = this.fСерия;
                // *** Start programmer edit section *** (паспортные.Серия Get end)

                // *** End programmer edit section *** (паспортные.Серия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (паспортные.Серия Set start)

                // *** End programmer edit section *** (паспортные.Серия Set start)
                this.fСерия = value;
                // *** Start programmer edit section *** (паспортные.Серия Set end)

                // *** End programmer edit section *** (паспортные.Серия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "паспортныеДанныеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View паспортныеДанныеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("паспортныеДанныеE", typeof(IIS.Test.паспортные));
                }
            }
            
            /// <summary>
            /// "паспортныеДанныеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View паспортныеДанныеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("паспортныеДанныеL", typeof(IIS.Test.паспортные));
                }
            }
        }
    }
}
